### ISSUE TITLE
 No such file or directory: 'configs/dtu.yaml'

### ISSUE THREAD

**Issue by zhao-you-fei** [svip-lab/FastMVSNet#19]
python E:\桌面\test\FastMVSNet\fastmvsnet/train.py --cfg configs/dtu.yaml
Traceback (most recent call last):
  File "E:\桌面\test\FastMVSNet\fastmvsnet/train.py", line 293, in <module>
    main()
  File "E:\桌面\test\FastMVSNet\fastmvsnet/train.py", line 271, in main
    cfg = load_cfg_from_file(args.config_file)
  File "E:\桌面\test\FastMVSNet\fastmvsnet/..\fastmvsnet\config.py", line 163, in load_cfg_from_file
    with open(configs, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/dtu.yaml'

**Comment by niujinshuchong** [comment]
@zhao-you-fei 
The code is tested on a Linux system. On a Windows system, the format of data path may be different. You may change it youself.
