### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by huanghailiang** [svip-lab/FastMVSNet#2]
my data file: 
--data
  --dtu2
    --Cameras
    --Depths
    --Eval
    --Rectified

**when I run the test with the pretrained model, I got some erro:**

2020-04-17 13:49:42,045 fastmvsnet INFO: Using 1 GPUs
2020-04-17 13:49:42,046 fastmvsnet INFO: Namespace(config_file='configs/dtu.yaml', cpu=False, opts=['TEST.WEIGHT', 'outputs/pretrained.pth'])
2020-04-17 13:49:42,046 fastmvsnet INFO: Loaded configuration file configs/dtu.yaml
2020-04-17 13:49:42,047 fastmvsnet INFO: Running with config:
AUTO_RESUME: True
DATA:
  NUM_WORKERS: 16
  TEST:
    IMG_HEIGHT: 960
    IMG_WIDTH: 1280
    INTER_SCALE: 2.13
    NUM_VIEW: 5
    NUM_VIRTUAL_PLANE: 96
    ROOT_DIR: data/dtu2
  TRAIN:
    INTER_SCALE: 4.24
    NUM_VIEW: 3
    NUM_VIRTUAL_PLANE: 48
    ROOT_DIR: data/dtu2
  VAL:
    NUM_VIEW: 3
    ROOT_DIR: data/dtu
MODEL:
  EDGE_CHANNELS: (32, 32, 64)
  FLOW_CHANNELS: (64, 64, 16, 1)
  IMG_BASE_CHANNELS: 8
  NUM_VIRTUAL_PLANE: 48
  TEST:
    IMG_SCALES: (0.25, 0.5)
    INTER_SCALES: (0.75, 0.15)
  TRAIN:
    IMG_SCALES: (0.25, 0.5)
    INTER_SCALES: (0.75, 0.375)
  VAL:
    IMG_SCALES: (0.125, 0.25)
    INTER_SCALES: (0.75, 0.375)
  VALID_THRESHOLD: 8.0
  VOL_BASE_CHANNELS: 8
  WEIGHT:
OUTPUT_DIR: @
RNG_SEED: 1
SCHEDULER:
  INIT_EPOCH: 4
  MAX_EPOCH: 4
  MultiStepLR:
    gamma: 0.1
    milestones: ()
  StepLR:
    gamma: 0.9
    step_size: 2
  TYPE: StepLR
SOLVER:
  BASE_LR: 0.0005
  RMSprop:
    alpha: 0.9
  SGD:
    momentum: 0.9
  TYPE: RMSprop
  WEIGHT_DECAY: 0.001
TEST:
  AUGMENTATION: ()
  BATCH_SIZE: 1
  LOG_PERIOD: 10
  WEIGHT: outputs/pretrained.pth
TRAIN:
  AUGMENTATION: ()
  BATCH_SIZE: 3
  CHECKPOINT_PERIOD: 1
  FROZEN_PATTERNS: ()
  LOG_PERIOD: 10
  VAL_METRIC: <1_cor
  VAL_PERIOD: 0
2020-04-17 13:49:44,768 fastmvsnet.utils.checkpoint INFO: Loading checkpoint from outputs/pretrained.pth
Traceback (most recent call last):
  File "fastmvsnet/test.py", line 141, in <module>
    main()
  File "fastmvsnet/test.py", line 137, in main
    test(cfg, output_dir, isCPU=isCPU)
  File "fastmvsnet/test.py", line 103, in test
    isCPU=isCPU,
  File "fastmvsnet/test.py", line 63, in test_model
    for iteration, data_batch in enumerate(data_loader):
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\software\work_tool\Anaconda3\envs\MVSNet_pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\FastMVSNet\fastmvsnet/..\fastmvsnet\dataset.py", line 271, in __getitem__
    h_scale = float(self.height) / images[0].shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by huanghailiang** [comment]
sorry，my path is erro

**Comment by Gocobnus** [comment]
我也遇到了这个问题 可以提供一下正确的文件夹格式么 谢谢 @huanghailiang

**Comment by AsDeadAsADodo** [comment]
> 我也遇到了这个问题 可以提供一下正确的文件夹格式么 谢谢 @huanghailiang

/data/dtu/Eval/Rectified/scan*
