### ISSUE TITLE
ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by 1299246210** [svip-lab/FastMVSNet#20]
After epoch 0 is successfully executed,I get two valueerror, 
1.ValueError: Caught ValueError in DataLoader worker process 0. 
2.ValueError: all input arrays must have the same shape.
How to slove them?  Thanks a lot!

The error code is as follows:

Traceback (most recent call last):
  File "fastmvsnet/train.py", line 293, in <module>
    main()
  File "fastmvsnet/train.py", line 289, in main
    train(cfg, output_dir)
  File "fastmvsnet/train.py", line 224, in train
    output_dir=output_dir,
  File "fastmvsnet/train.py", line 66, in train_model
    for iteration, data_batch in enumerate(data_loader):
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "fastmvsnet/../fastmvsnet/dataset.py", line 134, in __getitem__
    img_list = np.stack(images, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/dell/anaconda3/envs/fast/lib/python3.6/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by niujinshuchong** [comment]
@1299246210 

It is the problem of dataflow. Please check whether you have downloaded the training set completely.

**Comment by 1299246210** [comment]
> @1299246210
> 
> It is the problem of dataflow. Please check whether you have downloaded the training set completely.

Yes，you are right,thanks a lot!

**Comment by zhaojiacheng123456** [comment]
i have the same problem.it means i need to download the training again.the csv is not fit the train datasets

**Comment by CindyCxy** [comment]
What should be done to fix the same problem that occurs when testing with your own dataset?Is it because of the missing depth map folder?
