### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by 1299246210** [svip-lab/FastMVSNet#22]
During the testing phase，after  run the following code，which means the some pictures in scan1 and scan4 have been dealt with. 
I get two errors: 

AttributeError: Caught AttributeError in DataLoader worker process 2.
AttributeError: 'NoneType' object has no attribute 'shape'

The error code is as fllows:

update: 0
update: 1
2021-04-22 16:27:10,891 fastmvsnet.train INFO: data/dtu2/Eval/Rectified/scan1/rect_001_3_r5000.png finished.time: 5.5368 (5.5368)  data: 2.6959 (2.6959)
update: 0
update: 1
（rect_002-048）...
update: 0
update: 1
2021-04-22 16:28:40,953 fastmvsnet.train INFO: data/dtu2/Eval/Rectified/scan1/rect_049_3_r5000.png finished.time: 1.8685 (1.9510)  data: 1.3091 (1.3450)
update: 0
update: 1
2021-04-22 16:28:42,829 fastmvsnet.train INFO: data/dtu2/Eval/Rectified/scan4/rect_001_3_r5000.png finished.time: 1.8694 (1.9495)  data: 1.3101 (1.3443)
（rect_002-048）...
update: 0
update: 1
2021-04-22 16:30:12,374 fastmvsnet.train INFO: data/dtu2/Eval/Rectified/scan4/rect_049_3_r5000.png finished.time: 1.8616 (1.9084)  data: 1.3024 (1.3254)
Traceback (most recent call last):
  File "fastmvsnet/test.py", line 141, in <module>
    main()
  File "fastmvsnet/test.py", line 137, in main
    test(cfg, output_dir, isCPU=isCPU)
  File "fastmvsnet/test.py", line 103, in test
    isCPU=isCPU,
  File "fastmvsnet/test.py", line 63, in test_model
    for iteration, data_batch in enumerate(data_loader):
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dell/anaconda3/envs/fas/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "fastmvsnet/../fastmvsnet/dataset.py", line 271, in __getitem__
    h_scale = float(self.height) / images[0].shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by niujinshuchong** [comment]
hi, please refer to #2
