### ISSUE TITLE
test

### ISSUE THREAD

**Issue by LiuJinhui123** [svip-lab/FastMVSNet#25]
fastmvsnet.utils.checkpoint INFO: Loading checkpoint from /home/camellia/fastMVSNet-master/outputs/pretrained.pth
Traceback (most recent call last):
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 141, in <module>
    main()
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 137, in main
    test(cfg, output_dir, isCPU=isCPU)
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 98, in test
    test_model(model,
  File "/home/camellia/fastMVSNet-master/fastmvsnet/test.py", line 63, in test_model
    for iteration, data_batch in enumerate(data_loader):
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/camellia/anaconda3/envs/my/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/camellia/fastMVSNet-master/fastmvsnet/../fastmvsnet/dataset.py", line 271, in __getitem__
    h_scale = float(self.height) / images[0].shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by niujinshuchong** [comment]
Hi, please refer to #2
