### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by xuwendy** [svip-lab/FastMVSNet#8]
请问，我在运行train文件的时候出现了ImportError是怎么回事呢？具体如下
  File "/code/FastMVSNet-master/fastmvsnet/train.py", line 13, in <module>
    from fastmvsnet.utils.io import mkdir
  File "/code/FastMVSNet-master/fastmvsnet/../fastmvsnet/utils/io.py", line 7, in <module>
    import cv2
  File "/opt/conda/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libXau.so.6: cannot open shared object file: No such file or directory
百忙之中打扰您了，希望您能抽空给我解惑，感激不尽

**Comment by niujinshuchong** [comment]
@xuwendy 

应该是你的opencv没有装成功。

**Comment by zhao-you-fei** [comment]
Traceback (most recent call last):
  File "E:\桌面\test\FastMVSNet\fastmvsnet\train.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by Xiqiao-Zhao** [comment]
> Traceback (most recent call last):
> File "E:\桌面\test\FastMVSNet\fastmvsnet\train.py", line 9, in
> import torch
> ModuleNotFoundError: No module named 'torch'
应该是没安装pytorch
